### ISSUE TITLE
from urllib3.exceptions import DependencyWarning / ImportError: cannot import name DependencyWarning

### ISSUE THREAD

**Issue by brianjmurrell** [Freso/script.module.requests#20]
Since updating this addon in my Kodi Krypton installation from 2.12.4 to 2.18.4 I am getting the following errors:

```
06:48:58.914 T:2766400320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name DependencyWarning
                                            Traceback (most recent call last):
                                              File "/home/mythtv/.kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 3, in <module>
                                                from youtube_plugin.kodion.impl import Context
                                              File "/home/mythtv/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/home/mythtv/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 90, in <module>
                                                from urllib3.exceptions import DependencyWarning
                                            ImportError: cannot import name DependencyWarning
                                            -->End of Python script error report<--
```

But I do have the required version of _script.module.urllib3_:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.module.urllib3"
       name="urllib3"
       version="1.22"
       provider-name="shazow">
  <requires>
    <import addon="xbmc.python" version="2.25.0"/>
  </requires>
  <extension point="xbmc.python.module"
             library="lib" />
  <extension point="xbmc.addon.metadata">
    <summary lang="en_GB">urllib3 is a powerful, sanity-friendly HTTP client for Python</summary>
    <description lang="en_GB">Packed for KODI from https://github.com/shazow/urllib3</description>
    <platform>all</platform>
    <language></language>
    <license>MIT</license>
    <forum></forum>
    <website>https://urllib3.readthedocs.io/en/latest/</website>
    <source>https://github.com/beenje/script.module.urllib3</source>
    <email>beenje AT gmail.com</email>
  </extension>
</addon>

```

**Comment by brianjmurrell** [comment]
Interesting.  It seems that my Kodi installation is using the system installed urllib3 rather than the script.module.urllib3 one.  I discovered this by [re]moving the system package and now Kodi reports:

```
07:14:11.152 T:2596510528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib3
                                            Traceback (most recent call last):
                                              File "/home/mythtv/.kodi/addons/script.trakt/default.py", line 6, in <module>
                                                from resources.lib.service import traktService
                                              File "/home/mythtv/.kodi/addons/script.trakt/resources/lib/service.py", line 19, in <module>
                                                from resources.lib.traktapi import traktAPI
                                              File "/home/mythtv/.kodi/addons/script.trakt/resources/lib/traktapi.py", line 8, in <module>
                                                from trakt import Trakt
                                              File "/home/mythtv/.kodi/addons/script.module.trakt/lib/trakt/__init__.py", line 3, in <module>
                                                from trakt.client import TraktClient
                                              File "/home/mythtv/.kodi/addons/script.module.trakt/lib/trakt/client.py", line 5, in <module>
                                                from trakt.core.http import HttpClient
                                              File "/home/mythtv/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 8, in <module>
                                                from trakt.core.request import TraktRequest
                                              File "/home/mythtv/.kodi/addons/script.module.trakt/lib/trakt/core/request.py", line 3, in <module>
                                                from requests import Request
                                              File "/home/mythtv/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3
                                            -->End of Python script error report<--
```

instead of the _import name_ error previously.

So the question becomes, why is Kodi using system packages rather than the _script.module.*_ packages?

Here is the _debug_ for the _CPythonInvoker_ for one such module:

```
07:32:57.643 T:2623306560   DEBUG: CPythonInvoker(50, /home/mythtv/.kodi/addons/script.trakt/default.py): setting the Python path to /home/mythtv/.kodi/addons/script.trakt:/home/mythtv/.kodi/addons/script.module.addon.signals/lib:/home/mythtv/.kodi/addons/script.module.arrow/lib:/home/mythtv/.kodi/addons/script.module.dateutil/lib:/home/mythtv/.kodi/addons/script.module.requests/lib:/home/mythtv/.kodi/addons/script.module.simplejson/lib:/home/mythtv/.kodi/addons/script.module.six/lib:/home/mythtv/.kodi/addons/script.module.trakt/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-i386-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
```

While it has the _script.module.requests/lib_ in it's Python path, It seems to be missing _script.module.requests_' dependencies.  Any idea why this would be?

**Comment by beenje** [comment]
That's strange.
You can check in System settings -> Add-ons -> Manage dependencies that urllib3 is not disabled.

Anyway this is not an issue with the script.module.requests add-on but with Kodi itself.
You can create a bug report here: https://trac.kodi.tv
I'd recommend trying the forum first https://forum.kodi.tv

**Comment by brianjmurrell** [comment]
I don't have a _Manage dependencies_ in _System settings_ -> _Add-ons_.  I am using the _Confluence_ skin on Krypton though (for UI consistency with previous Kodi versions).

I was wondering myself how to enable/disable/update/etc. _script.module.*_ type addons.

https://trac.kodi.tv/ticket/17652 FWIW.

**Comment by beenje** [comment]
This is with the Estuary skin. You could just switch to it to check.

I'll close this issue. Thanks for creating one for Kodi.

**Comment by brianjmurrell** [comment]
So yeah.  Wow.  It was that _script.module.requests_' dependencies were disabled.  Why would those have been disabled if they are required by _script.module.requests_?  I know **I** didn't disable those as this update happened just the last day or two and I would certainly remember disabling them.  Heck, I didn't even know they could be disabled.

**Comment by beenje** [comment]
Thanks for the feedback.
Yes, something strange here. Let's see what Kodi dev say in your ticket.
