### ISSUE TITLE
ImportError: cannot import name utils

### ISSUE THREAD

**Issue by LS80** [Freso/script.module.requests#4]
A user of one of my addons gets an ImportError from requests

```
13:43:45  84.481079 T:2881483840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                        Error Type: <type 'exceptions.ImportError'>
                                        Error Contents: cannot import name utils
                                        Traceback (most recent call last):
                                          File "/storage/.kodi/addons/script.openelec.devupdate/default.py", line 517, in <module>
                                            from resources.lib import builds
                                          File "/storage/.kodi/addons/script.openelec.devupdate/resources/lib/builds.py", line 11, in <module>
                                            import requests
                                          File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 58, in <module>
                                            from . import utils
                                        ImportError: cannot import name utils
```

Have you seen this before? I've not been able to reproduce it.

**Comment by beenje** [comment]
No never saw that. Strange.
It looks like the script.module.requests addon was not installed properly.
Maybe there is no space left on the device?
I would ask him to do "ls /storage/.kodi/addons/script.module.requests/lib/requests/".

He could try forcing to re-install the addon:

``` bash
cd /storage/.kodi/addons
rm -rf script.module.requests
rm packages/script.module.requests-*
rm -rf script.openelec.devupdate
```

And re-isntall the script.openelec.devupdate addon from XBMC interface.
