### ISSUE TITLE
Plugin crash in debian jessie xbmc gotham ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD, AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by susobaco** [Freso/script.module.requests#5]
the log:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type:
  Error Contents: 'module' object has no attribute 'PROTOCOL_SSLv3'
  Traceback (most recent call last):
  File "/home/xbmc/.xbmc/addons/plugin.video.p2p-streams/default.py", line 14, in
  from resources.core import sopcast as sop
  File "/home/xbmc/.xbmc/addons/plugin.video.p2p-streams/resources/core/sopcast.py", line 11, in
  import xbmc,xbmcgui,xbmcplugin,urllib2,os,sys,subprocess,xbmcvfs,socket,re,requests,shutil
  File "/home/xbmc/.xbmc/addons/script.module.requests/lib/requests/init.py", line 53, in
  from .packages.urllib3.contrib import pyopenssl
  File "/home/xbmc/.xbmc/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in
  ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
  AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
  -->End of Python script error report<--

**Comment by beenje** [comment]
Problem was fixed in urllib3 by this commit https://github.com/dstufft/urllib3/commit/b9b3b0102ead7ad8ad086c39737f22ddefa7e626 and in requests here https://github.com/kennethreitz/requests/commit/7aa6c62d6d917e11f81b166d1d6c9e60340783ac

I'll update to requests v2.5.3 to fix the issue.

**Comment by beenje** [comment]
Fixed by 24adf70c6d29dcb693ba232588533f1b8e3e291e
